sudo: false
language: python
python:
  - 3.5
install:
  - "pip install -r test_requirements.txt"
  - "npm install -g jshint"
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "nvm install stable"
script: nosetests src/py/tests.py
cache: pip